input {
    file {
        path => "/home/cowrie/cowrie/var/log/cowrie/cowrie.json"
        codec => json
        start_position => "beginning"
    }
}

filter {
    geoip {
        source => "src_ip"
        target => "geoip"
    }
}

output {
    elasticsearch {
        hosts => ["https://localhost:9200"]
        index => "cowrie-log-%{+YYYY.MM.dd}"
        user => "elastic"
        password => "Fa2RY*6Qb*P94+YBdlba"
        ssl_certificate_verification => false
    }
}
